apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: chinmay024/client
          resources:
            limits:
              memory: "256Mi" # Set the desired memory limit
              cpu: "200m"     # Set the desired CPU limit
            requests:
              memory: "128Mi" # Set the desired memory request
              cpu: "100m"     # Set the desired CPU request
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
